import { sql } from 'drizzle-orm';
import * as schema from './db/schema/schema.js';
import type { App } from './index.js';

const serversData = [
  {
    name: 'US - New York #1',
    country: 'United States',
    countryCode: 'US',
    city: 'New York',
    ipAddress: '198.51.100.1',
    protocol: 'WireGuard',
    load: 23,
    isTor: false,
    isPremium: false,
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    name: 'US - New York #2',
    country: 'United States',
    countryCode: 'US',
    city: 'New York',
    ipAddress: '198.51.100.2',
    protocol: 'OpenVPN',
    load: 67,
    isTor: false,
    isPremium: false,
    latitude: 40.7128,
    longitude: -74.006,
  },
  {
    name: 'US - Los Angeles #1',
    country: 'United States',
    countryCode: 'US',
    city: 'Los Angeles',
    ipAddress: '198.51.100.3',
    protocol: 'WireGuard',
    load: 45,
    isTor: false,
    isPremium: true,
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    name: 'US - Chicago #1',
    country: 'United States',
    countryCode: 'US',
    city: 'Chicago',
    ipAddress: '198.51.100.4',
    protocol: 'OpenVPN',
    load: 31,
    isTor: false,
    isPremium: false,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    name: 'US - Chicago #2 (Tor)',
    country: 'United States',
    countryCode: 'US',
    city: 'Chicago',
    ipAddress: '198.51.100.5',
    protocol: 'WireGuard',
    load: 55,
    isTor: true,
    isPremium: true,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    name: 'UK - London #1',
    country: 'United Kingdom',
    countryCode: 'GB',
    city: 'London',
    ipAddress: '198.51.100.6',
    protocol: 'WireGuard',
    load: 72,
    isTor: false,
    isPremium: false,
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    name: 'UK - London #2 (Tor)',
    country: 'United Kingdom',
    countryCode: 'GB',
    city: 'London',
    ipAddress: '198.51.100.7',
    protocol: 'OpenVPN',
    load: 38,
    isTor: true,
    isPremium: false,
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    name: 'DE - Frankfurt #1',
    country: 'Germany',
    countryCode: 'DE',
    city: 'Frankfurt',
    ipAddress: '198.51.100.8',
    protocol: 'WireGuard',
    load: 19,
    isTor: false,
    isPremium: false,
    latitude: 50.1109,
    longitude: 8.6821,
  },
  {
    name: 'DE - Frankfurt #2',
    country: 'Germany',
    countryCode: 'DE',
    city: 'Frankfurt',
    ipAddress: '198.51.100.9',
    protocol: 'OpenVPN',
    load: 84,
    isTor: false,
    isPremium: true,
    latitude: 50.1109,
    longitude: 8.6821,
  },
  {
    name: 'NL - Amsterdam #1',
    country: 'Netherlands',
    countryCode: 'NL',
    city: 'Amsterdam',
    ipAddress: '198.51.100.10',
    protocol: 'WireGuard',
    load: 61,
    isTor: false,
    isPremium: false,
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    name: 'NL - Amsterdam #2 (Tor)',
    country: 'Netherlands',
    countryCode: 'NL',
    city: 'Amsterdam',
    ipAddress: '198.51.100.11',
    protocol: 'WireGuard',
    load: 44,
    isTor: true,
    isPremium: false,
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    name: 'CA - Toronto #1',
    country: 'Canada',
    countryCode: 'CA',
    city: 'Toronto',
    ipAddress: '198.51.100.12',
    protocol: 'WireGuard',
    load: 28,
    isTor: false,
    isPremium: false,
    latitude: 43.6532,
    longitude: -79.3832,
  },
  {
    name: 'CA - Vancouver #1',
    country: 'Canada',
    countryCode: 'CA',
    city: 'Vancouver',
    ipAddress: '198.51.100.13',
    protocol: 'OpenVPN',
    load: 52,
    isTor: false,
    isPremium: false,
    latitude: 49.2827,
    longitude: -123.1207,
  },
  {
    name: 'JP - Tokyo #1',
    country: 'Japan',
    countryCode: 'JP',
    city: 'Tokyo',
    ipAddress: '198.51.100.14',
    protocol: 'WireGuard',
    load: 76,
    isTor: false,
    isPremium: true,
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    name: 'SG - Singapore #1',
    country: 'Singapore',
    countryCode: 'SG',
    city: 'Singapore',
    ipAddress: '198.51.100.15',
    protocol: 'WireGuard',
    load: 88,
    isTor: false,
    isPremium: false,
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    name: 'AU - Sydney #1',
    country: 'Australia',
    countryCode: 'AU',
    city: 'Sydney',
    ipAddress: '198.51.100.16',
    protocol: 'OpenVPN',
    load: 33,
    isTor: false,
    isPremium: false,
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    name: 'FR - Paris #1',
    country: 'France',
    countryCode: 'FR',
    city: 'Paris',
    ipAddress: '198.51.100.17',
    protocol: 'WireGuard',
    load: 47,
    isTor: false,
    isPremium: false,
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    name: 'CH - Zurich #1',
    country: 'Switzerland',
    countryCode: 'CH',
    city: 'Zurich',
    ipAddress: '198.51.100.18',
    protocol: 'WireGuard',
    load: 15,
    isTor: false,
    isPremium: true,
    latitude: 47.3769,
    longitude: 8.5417,
  },
  {
    name: 'SE - Stockholm #1',
    country: 'Sweden',
    countryCode: 'SE',
    city: 'Stockholm',
    ipAddress: '198.51.100.19',
    protocol: 'OpenVPN',
    load: 29,
    isTor: false,
    isPremium: false,
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    name: 'SE - Stockholm #2 (Tor)',
    country: 'Sweden',
    countryCode: 'SE',
    city: 'Stockholm',
    ipAddress: '198.51.100.20',
    protocol: 'WireGuard',
    load: 63,
    isTor: true,
    isPremium: false,
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    name: 'BR - São Paulo #1',
    country: 'Brazil',
    countryCode: 'BR',
    city: 'São Paulo',
    ipAddress: '198.51.100.21',
    protocol: 'WireGuard',
    load: 41,
    isTor: false,
    isPremium: false,
    latitude: -23.5505,
    longitude: -46.6333,
  },
  {
    name: 'BR - São Paulo #2',
    country: 'Brazil',
    countryCode: 'BR',
    city: 'São Paulo',
    ipAddress: '198.51.100.22',
    protocol: 'OpenVPN',
    load: 57,
    isTor: false,
    isPremium: false,
    latitude: -23.5505,
    longitude: -46.6333,
  },
];

export async function seedServers(app: App) {
  try {
    const existingServers = await app.db.select().from(schema.servers).limit(1);

    if (existingServers.length === 0) {
      app.logger.info('Seeding VPN servers');
      await app.db.insert(schema.servers).values(serversData).onConflictDoNothing();
      app.logger.info({ count: serversData.length }, 'VPN servers seeded successfully');
    }
  } catch (error) {
    app.logger.error({ err: error }, 'Failed to seed VPN servers');
  }
}
